[book]
authors = ["Phodal Huang"]
language = "zh-cn"
multilingual = false
src = "src"
title = "构筑大语言模型应用"

[output.html]
git-repository-url = "https://github.com/phodal/aigc"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/phodal/aigc/edit/master/{path}"
site-url = "/"
cname = "aigc.phodal.com"

# cargo install mdbook-epub
# mdbook-epub --standalone ./path/to/book/dir
[output.epub]