[package]
name = "mdbook-count"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.30"
serde = "~1.0"
serde_derive = "~1.0"
lazy_static = "~1.4"
words-count = "0.1.5"
